Create footer.html
VladimirBludov/ice-cream pull request #3
Opened 2021-11-30 19:40 UTC by Lezhnova

2021-11-30 19:51 UTC, VladimirBludov requested changes

2021-11-30 19:51 UTC, VladimirBludov commented on src/partials/footer.html
> +</footer>
Добавь пустую строку в конце

2021-11-30 21:18 UTC, VladimirBludov commented
Добавь футер в index.html, с помощью include

2021-12-01 13:43 UTC, Lezhnova commented on src/partials/footer.html
> +</footer>
Готово)

2021-12-01 13:56 UTC, VladimirBludov approved these changes

2021-12-01 13:56 UTC, merged